export const ActionTypes = {
   GET_ERRORS: "GET_ERRORS",
   SET_CURRENT_USER: "SET_CURRENT_USER",
   GET_PROFILE: "GET_PROFILE",
   GET_PROFILES: "GET_PROFILES",
   PROFILE_LOADING: "PROFILE_LOADING",
   CLEAR_CURRENT_PROFILE: "CLEAR_CURRENT_PROFILE",
   CREATE_PROFILE: "CREATE_PROFILE",
   PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
}